package gr.adr.xplora.admin.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PromptAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPromptAllPropertiesEquals(Prompt expected, Prompt actual) {
        assertPromptAutoGeneratedPropertiesEquals(expected, actual);
        assertPromptAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPromptAllUpdatablePropertiesEquals(Prompt expected, Prompt actual) {
        assertPromptUpdatableFieldsEquals(expected, actual);
        assertPromptUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPromptAutoGeneratedPropertiesEquals(Prompt expected, Prompt actual) {
        assertThat(expected)
            .as("Verify Prompt auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPromptUpdatableFieldsEquals(Prompt expected, Prompt actual) {
        assertThat(expected)
            .as("Verify Prompt relevant properties")
            .satisfies(e -> assertThat(e.getKey()).as("check key").isEqualTo(actual.getKey()))
            .satisfies(e -> assertThat(e.getValue()).as("check value").isEqualTo(actual.getValue()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPromptUpdatableRelationshipsEquals(Prompt expected, Prompt actual) {
        assertThat(expected)
            .as("Verify Prompt relationships")
            .satisfies(e -> assertThat(e.getLanguage()).as("check language").isEqualTo(actual.getLanguage()));
    }
}
